server:
  port: 8080

spring:
  application:
    name: RENTAL-STORE
  config:
    import:
      - 'configserver:http://localhost:8888'
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_store?currentSchema=rental_store
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect
