server:
  port: 8080
  servlet:
    context-path: /api/customer
spring:
  application:
    name: customer
  config:
    import:
      - 'configserver:http://localhost:8888'
  datasource:
    url: jdbc:postgresql://192.168.1.8:5432/rental_store
    username: alert
    password: 'alert0!'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true