spring:
  datasource:
    url: jdbc:postgresql://192.168.1.8:5432/loldb
    username: lol
    password: lol1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
