spring:
  application:
    name: API-GATEWAY
  config:
    import:
      - 'configserver:http://localhost:8888'
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: lb://customer
          predicates:
            - Path=/customers/**
        - id: address-route
          uri: lb:RENTAL-STORE
          predicates:
            - Path=/addresses/**
        - id: city-route
          uri: lb:RENTAL-STORE
          predicates:
            - Path=/cities/**
        - id: country-route
          uri: lb:RENTAL-STORE
          predicates:
            - Path=/countries/**
#            - Path=/addresses/**
#            - Path=/cities/**
#            - Path=/countries/**
# Secondo il corso dovrei fare una sezione (- id...) per ogni servizio, ma sono tutti sotto lo stesso yml quindi hanno tutti lo stesso id

server:
  port: 9090