spring:
  application:
    name: API-GATEWAY
  config:
    import:
      - 'configserver:http://localhost:8888'
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/customer/**

server:
  port: 9090